/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Anchor: typeof import('./components/Anchor.vue')['default']
    Auth: typeof import('./components/Auth.vue')['default']
    ButtonDark: typeof import('./components/ButtonDark.vue')['default']
    Chatbot: typeof import('./components/Chatbot.vue')['default']
    DatabaseKey: typeof import('./components/DatabaseKey.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    README: (typeof import("./components/README.md"))["default"]
    Request: typeof import('./components/Request.vue')['default']
    RouterBack: typeof import('./components/RouterBack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Stateful: typeof import('./components/Stateful.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: (typeof import("./components/TheFooter.vue"))["default"]
    TheInput: typeof import('./components/TheInput.vue')['default']
    TimeLine: typeof import('./components/TimeLine.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
    Websocket: typeof import('./components/Websocket.vue')['default']
  }
}
